services:
  - type: web
    name: friolog-giri
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD_HASH
        sync: false   # da impostare manualmente su Render dashboard
    disk:
      name: db
      mountPath: /opt/render/project/src/instance
      sizeGB: 1
